// <auto-generated />

using DataBaseModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EsBot.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260410115104_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EsBot.Server.DbModelss.TestModel", b =>
                {
                    b.Property<string>("HelloWorld")
                        .HasColumnType("text");

                    b.Property<string>("HelloWorld2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HelloWorld3")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("HelloWorld");

                    b.ToTable("TestModels");
                });
#pragma warning restore 612, 618
        }
    }
}
