// <auto-generated />
using System;
using DataBaseModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EsBot.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EsBot.Server.DbModels.EvaluationResult", b =>
                {
                    b.Property<int>("SubmittedAnswerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EvaluatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.HasKey("SubmittedAnswerId");

                    b.ToTable("EvaluationResults");
                });

            modelBuilder.Entity("EsBot.Server.DbModels.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Role")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserSessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserSessionId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("EsBot.Server.DbModels.QuizItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ExpectedAnswerCriteria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QuizRequestId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QuizRequestId");

                    b.ToTable("QuizItems");
                });

            modelBuilder.Entity("EsBot.Server.DbModels.QuizRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("UserSessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserSessionId");

                    b.ToTable("QuizRequests");
                });

            modelBuilder.Entity("EsBot.Server.DbModels.SubmittedAnswer", b =>
                {
                    b.Property<int>("QuizItemId")
                        .HasColumnType("integer");

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("QuizItemId");

                    b.ToTable("SubmittedAnswers");
                });

            modelBuilder.Entity("EsBot.Server.DbModels.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("LastInteractionAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExternalUserId");

                    b.ToTable("UserSessions");
                });

            modelBuilder.Entity("EsBot.Server.DbModels.EvaluationResult", b =>
                {
                    b.HasOne("EsBot.Server.DbModels.SubmittedAnswer", "SubmittedAnswer")
                        .WithOne("Evaluation")
                        .HasForeignKey("EsBot.Server.DbModels.EvaluationResult", "SubmittedAnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubmittedAnswer");
                });

            modelBuilder.Entity("EsBot.Server.DbModels.Message", b =>
                {
                    b.HasOne("EsBot.Server.DbModels.UserSession", "UserSession")
                        .WithMany("Messages")
                        .HasForeignKey("UserSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserSession");
                });

            modelBuilder.Entity("EsBot.Server.DbModels.QuizItem", b =>
                {
                    b.HasOne("EsBot.Server.DbModels.QuizRequest", "QuizRequest")
                        .WithMany("QuizItems")
                        .HasForeignKey("QuizRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuizRequest");
                });

            modelBuilder.Entity("EsBot.Server.DbModels.QuizRequest", b =>
                {
                    b.HasOne("EsBot.Server.DbModels.UserSession", "UserSession")
                        .WithMany("QuizRequests")
                        .HasForeignKey("UserSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserSession");
                });

            modelBuilder.Entity("EsBot.Server.DbModels.SubmittedAnswer", b =>
                {
                    b.HasOne("EsBot.Server.DbModels.QuizItem", "QuizItem")
                        .WithOne("SubmittedAnswer")
                        .HasForeignKey("EsBot.Server.DbModels.SubmittedAnswer", "QuizItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuizItem");
                });

            modelBuilder.Entity("EsBot.Server.DbModels.QuizItem", b =>
                {
                    b.Navigation("SubmittedAnswer");
                });

            modelBuilder.Entity("EsBot.Server.DbModels.QuizRequest", b =>
                {
                    b.Navigation("QuizItems");
                });

            modelBuilder.Entity("EsBot.Server.DbModels.SubmittedAnswer", b =>
                {
                    b.Navigation("Evaluation");
                });

            modelBuilder.Entity("EsBot.Server.DbModels.UserSession", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("QuizRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
